WikiProfes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuario.urls')),
    path('', include('publicacion.urls')),
    path('', include('materia.urls')),
    path('', include('profesor.urls')),
]

materia/urls.py
from django.urls import path
from . import views

app_name = 'materia'
urlpatterns = [
    path('materias', views.MateriasView.as_view(), name='materias'),
]

publicacion/urls.py
from django.urls import path
from . import views

app_name = 'publicacion'
urlpatterns = [
    path('profesor/<int:profesor_id>', views.ProfesorView.as_view(), name='profesor'),
    path('materia/<int:materia_id>', views.MateriaView.as_view(), name='materia'),
    path('<int:pk>/', views.DetallePublicacionView.as_view(), name='detalle'),
]

materia/models.py
from django.db import models
from profesor.models import Profesor
from django.contrib.auth.models import User

# Create your models here.
class Materia(models.Model):
    clave = models.CharField(max_length=10)
    nombre = models.CharField(max_length=80)
    departamento = models.CharField(max_length=50)
    profesores = models.ManyToManyField(Profesor, through='publicacion.Publicacion')
    usuarios = models.ManyToManyField(User, through='publicacion.Publicacion')

    def __str__(self):
        return f'{self.clave} {self.nombre}'

materia/views.py
from django.shortcuts import render
from django.views import generic
from itertools import groupby
from .models import Materia

# Create your views here.
class MateriasView(generic.ListView):
    template_name = 'pages/materias.html'
    
    context_object_name = 'departamentos'

    def get_queryset(self):
        return Materia.objects.order_by('departamento', 'nombre')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        materias = self.get_queryset()

        departamentos = {}

        for departamento, grupo in groupby(materias, lambda x: x.departamento):
            departamentos[departamento] = list(grupo)

        context['departamentos'] = departamentos

        return context

templates/pages/busqueda.html
{% extends "base.html" %}

{% block title %}
<title>Búsqueda</title>
{% endblock title %}

{% block content%}

<div style="margin-top: 3rem;">
    {% if busqueda %}
        <h5> Resultados de búsqueda para: {{busqueda}} </h5>
        {% if resultados %}
            {% for resultado in resultados %}
                {% if resultado.tipo == "profesor" %}
                    <div class="container" style="margin-top: 1rem;">
                        <div class="card">
                            <div class="card-body">
                            <h5 class="card-title">{{resultado.objeto.nombre}}</h5>
                            <a href="{% url 'publicacion:profesor' resultado.objeto.id %}" class="btn btn-primary">Ver perfil</a>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="container" style="margin-top: 1rem;">
                        <div class="card">
                            <div class="card-body">
                            <h5 class="card-title">{{resultado.objeto.nombre}}</h5>
                            <p class="card-text">{{resultado.objeto.clave}}</p>
                            <a class="btn btn-primary" href="{% url 'publicacion:materia' resultado.objeto.id %}">Ver detalles</a>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <h3> No se encontró nada</h3>
        {% endif %}
    {% else %}
        <h5>No has buscado nada 😿</h5>
    {% endif%}
</div>

{% endblock content%}

templates/pages/index.html
{% extends "base.html" %}

{% block title %}
<title>WikiProfes</title>
{% endblock title %}

{% block content %}

{% if messages%}
<div class="message">
    {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
            <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/>
        </svg>
        <strong>{{message}}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>
{% endif %}

{% if not user.is_authenticated %}
<div class="alert alert-warning" role="alert">
    Para poder crear publicaciones debes iniciar sesión o registrarte si aún no lo has hecho.
</div>
{% endif %}

<div style="margin-top: 3rem;">
    {% for publicacion in publicacion_list %}
    <section>
        <div class="container" style="margin-top: 1rem;">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">{{ publicacion.titulo }}</h5>
                    <h6 class="card-subtitle mb-2 text-body-secondary text-start">
                        <a href="{% url 'publicacion:materia' publicacion.materia.id %}">{{ publicacion.materia }}</a>
                    </h6>
                    <p class="card-text">{{ publicacion.comentario }}</p>
                    <h6 class="card-subtitle mb-2 text-body-secondary text-end">
                        Acerca de <a href="{% url 'publicacion:profesor' publicacion.profesor.id %}">{{ publicacion.profesor }}</a>
                    </h6>
                    <a href="{% url 'publicacion:detalle' publicacion.id %}" class="btn btn-primary mt-3">Ver más</a>
                </div>
                <div class="card-footer text-body-secondary">
                    Por {{ publicacion.usuario }} el {{ publicacion.fecha|date:"d M Y" }}
                </div>
            </div>
        </div>
    </section>
    {% endfor %}
</div>

{% if user.is_authenticated %}
<button type="button" onclick="window.location.replace('/crear-publicacion')" class="btn btn-outline-primary position-fixed bottom-0 end-0 mb-5 me-5">
    Crear publicación 
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
    </svg>
</button>
{% endif %}

{% endblock content %}

templates/pages/materias.html
{% extends "base.html" %}

{% block title  %}
<title>Materias</title>
{% endblock title  %}

{% block content %}

<div style="margin-top: 3rem;">
    {% for departamento, materias in departamentos.items %}
    <h3 style="text-align: center; padding: 1rem;">{{ departamento }}</h3>
    <div class="row" style="display: flex; flex-wrap: wrap; gap: 1rem; justify-content: flex-start;">
        {% for materia in materias %}
        <div class="container" style="flex: 1 1 calc(25% - 1rem); max-width: calc(25% - 1rem);">
            <div class="card" style="width: 100%; margin: 0 auto;">
                <div class="card-body">
                <h5 class="card-title">{{materia.nombre}}</h5>
                <p class="card-text">{{materia.clave}}</p>
                <a class="btn btn-primary" href="{% url 'publicacion:materia' materia.id %}">Ver detalles</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>

{% endblock content %}

templates/pages/profesores.html
{% extends "base.html" %}

{% block title %}
<title>Profesores</title>
{% endblock title %}

{% block content %}
<div style="margin-top: 3rem;">
    <section>
        {% for profesor in profesor_list %}
            <div class="container" style="margin-top: 1rem;">
                <div class="card">
                    <div class="card-body">
                      <h5 class="card-title">{{profesor.nombre}}</h5>
                      <p class="card-text">
                        {% for i in rangoEstrellas %}
                            {% if i <= profesor.promedioGeneral %}
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="gold" class="bi bi-star-fill" viewBox="0 0 16 16">
                                <path d="M3.612 15.443c-.396.198-.806-.149-.746-.592l.83-4.73-3.522-3.356c-.329-.314-.158-.888.283-.95l4.898-.696 2.18-4.327c.197-.39.73-.39.927 0l2.18 4.327 4.898.696c.441.062.612.636.283.95l-3.522 3.356.83 4.73c.06.443-.35.79-.746.592L8 13.187l-4.389 2.256z"/>
                            </svg>
                            {% else %}
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="lightgray" class="bi bi-star" viewBox="0 0 16 16">
                                <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.158-.888-.282-.95l-4.898-.696-2.18-4.327a.513.513 0 0 0-.927 0L5.354 5.69l-4.898.696c-.441.062-.612.636-.283.95l3.522 3.356-.83 4.73zm4.905-2.767L8 11.812l-1.771.92.339-1.93L5.024 8.522l1.937-.283L8 6.287l.839 1.952 1.937.283-1.543 1.418.339 1.93z"/>
                            </svg>
                            {% endif %}       
                        {% endfor %}
                      </p>
                      <a href="{% url 'publicacion:profesor' profesor.id %}" class="btn btn-primary">Ver perfil</a>
                    </div>
                  </div>
            </div>
        {% endfor %}
    </section>
</div>
{% endblock content %}