WikiProfes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuario.urls')),
    path('', include('publicacion.urls')),
    path('', include('materia.urls')),
    path('', include('profesor.urls')),
]

materia/urls.py
from django.urls import path
from . import views

app_name = 'materia'
urlpatterns = [
    path('materias', views.MateriasView.as_view(), name='materias'),
]

usuario/urls.py
from django.urls import path
from . import views

app_name = 'usuario'
urlpatterns = [
    path('registro', views.RegistroView.as_view(), name='registro'),
    path('inicio-sesion', views.InicioSesionView.as_view(), name='inicio-sesion'),
    path('', views.HomeView.as_view(), name='index'),
    path('logout', views.logOutRequest, name='logout'),
    path('crear-publicacion', views.CrearPublicacion.as_view(), name='crear-publicacion'),
    path('busqueda', views.busqueda, name='busqueda'),
]

templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block title %}
    <title>Wikiprofes</title>
    {% endblock title %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand">WikiProfes</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/profesores">Profesores</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/materias">Materias</a>
                </li>
            </ul>
            <form method="get" class="d-flex" role="search" action="{% url 'usuario:busqueda' %}">
                <input class="form-control me-2" type="search" placeholder="Profesor/Materia" aria-label="Search" name="busqueda">
                <button class="btn btn-outline-success" type="submit">Buscar</button>
            </form>
            <ul class="navbar-nav mb-2 mb-lg-0">
    
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link">Hola, {{user.username}}</a>
                    </li>
                    <li class="nav-item">
                        <a href="/logout" class="nav-link">Cerrar sesión</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="/inicio-sesion">Iniciar sesión</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/registro">Registrarse</a>
                    </li>
                {% endif %}
                
            </ul>
            </div>
        </div>
    </nav>
</head>
<body>
    {% block content %}
    {% endblock content %}
    {% block jscript %}
    {% endblock jscript %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/sesionBase.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block title %}
    <title>Wikiprofes</title>
    {% endblock title %}
    
</head>
<body>
    {% block content %}
    {% endblock content %}
    {% block jscript %}
    {% endblock jscript %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>